### ISSUE TITLE
Allow stateful comparators

### ISSUE THREAD

**Issue by asomers** [sekineh/binary-heap-plus-rs#11]
binary-heap-plus would be even more useful if it could employ stateful comparators.  They need not implement `FnMut(&T, &T) -> Ordering`.  Instead, it would be sufficient to add a  `BinaryHeap::get_comparator(&mut self) -> &mut C` method that would return a mutable reference to the current comparator function.

My application is a scheduler where operations are scheduled by an address.  The addresses wrap around, and the scheduling algorithm advances in one direction only (until it too wraps around).  It would be very intuitive to implement the scheduler with a binary heap whose comparator function used modulo arithmetic.  However, that would require updating the comparator function every time the scheduler advances.

**Comment by BatmanAoD** [comment]
By mutating the state of the stateful comparator, you change the heap invariant, so you'd need to re-hepify the entire collection, I think (I don't know of any way the `BinaryHeap` itself could introspect the comparator to determine a "smarter" approach). So I'm not sure I see an advantage in providing mutable stateful operators versus just transferring the collection from one heap to a new one with a different operator.

**Comment by asomers** [comment]
Well, in my case changing the comparator's state doesn't change the ordering of any current elements.  It only changes the relative ordering of current vs future elements.  Would that make a difference?

**Comment by BatmanAoD** [comment]
Not from the perspective of the library, I think, unless the mutation operation is made `unsafe`.

**Comment by sekineh** [comment]
I think example 2 below shows how to implement comparator update.

# Example 1) re-heapify

Re-heapify is done like below. Note that `.into_vec()` is very cheap (optimized to `self.data`).
```
    // Example 1) How to reconstruct heap using different comparator
    // caveat: `heap` and `heap2` are of different types because each closure have diferent types.
    let heap = BinaryHeap::from_vec_cmp(vec![1, 2, 3, 4, 5], |a: &i32, b: &i32| a.cmp(b));
    assert_eq!(heap.peek(), Some(&5));

    let heap2 = BinaryHeap::from_vec_cmp(heap.into_vec(), |a: &i32, b: &i32| b.cmp(a));
    assert_eq!(heap2.peek(), Some(&1));
```
In the example above, `heap1` and `heap2` have different types because each closure have different types in rust.

# Example 2) Use boxed closure

Need to reassign a new heap into the existing variable?  Use boxed closures to keep `BinaryHeap` types the same.
```
    // Example 2) Use boxed closure with explicit type.
    let cmp1: Box<Fn(&i32, &i32) -> Ordering> = Box::new(|a: &i32, b: &i32| a.cmp(b));
    let mut heap = BinaryHeap::from_vec_cmp(vec![1, 2, 3, 4, 5], cmp1);
    assert_eq!(heap.peek(), Some(&5));

    let cmp2: Box<Fn(&i32, &i32) -> Ordering> = Box::new(|a: &i32, b: &i32| b.cmp(a));
    heap = BinaryHeap::from_vec_cmp(heap.into_vec(), cmp2);
    assert_eq!(heap.peek(), Some(&1));
```

# Full source

rustc 1.35.0-beta.7 (2bafaaf66 2019-05-14)
binary-heap-plus = "0.2.0"
```
use binary_heap_plus::*;
use std::cmp::Ordering;

fn main() {
    // Example 1) How to reconstruct heap using different comparator
    // caveat: `heap` and `heap2` are of different types because each closure have diferent types.
    let heap1 = BinaryHeap::from_vec_cmp(vec![1, 2, 3, 4, 5], |a: &i32, b: &i32| a.cmp(b));
    assert_eq!(heap1.peek(), Some(&5));

    let heap2 = BinaryHeap::from_vec_cmp(heap1.into_vec(), |a: &i32, b: &i32| b.cmp(a));
    assert_eq!(heap2.peek(), Some(&1));

    // Example 2) Use boxed closure with explicit type.
    let cmp1: Box<Fn(&i32, &i32) -> Ordering> = Box::new(|a: &i32, b: &i32| a.cmp(b));
    let mut heap = BinaryHeap::from_vec_cmp(vec![1, 2, 3, 4, 5], cmp1);
    assert_eq!(heap.peek(), Some(&5));

    let cmp2: Box<Fn(&i32, &i32) -> Ordering> = Box::new(|a: &i32, b: &i32| b.cmp(a));
    heap = BinaryHeap::from_vec_cmp(heap.into_vec(), cmp2);
    assert_eq!(heap.peek(), Some(&1));
}
```

**Comment by sekineh** [comment]
1) I think the current API already supports comparator update use case by reconstructing `BinaryHeap`.
2) I don't think `BinaryHeap` should provide stateful comparison feature. If you provide actually stateful comparator on it, it is a logic error in user program.

**Comment by sekineh** [comment]
Quick note:
Comparator update use case is now better supported by #26.
