### ISSUE TITLE
insert with fall through

### ISSUE THREAD

**Issue by asafigan** [sekineh/binary-heap-plus-rs#6]
This is a feature request.

I am interesting in having a heap of a fixed size. To enforce this I would need a method that inserts into the heap without growing it. I was thinking of a method that takes an item to insert and returns an option. None is when the heap wasn't full. Some would mean that the heap was full and it holds that value that fell out which could be different than the item inserted. For a super simple example, if there is a heap of size 1 that only has a 2 in it and you try to insert 3, the 3 should replace the 2 and then Some(2) should be returned instead of the heap growing.

I don't know what a good name for this method would be.

**Comment by asafigan** [comment]
After looking at the implementation, I don't know if this is possible. I would like the method to return the smallest item but it doesn't look possible. If that is the cause than you can close this issue.

**Comment by sekineh** [comment]
Thanks for adding issue!

The implementation included in this crate is a normal binary heap derived from `std::collections::BinaryHeap`.  
Although I added custom comparator on it, still you can't retrieve/delete both of max and min values from the same heap instance.

I think you might find the following crate useful:
https://crates.io/crates/min-max-heap
> A min-max-heap is like a binary heap, but it allows extracting both the minimum and maximum value efficiently. In particular, finding either the minimum or maximum element is O(1). A removal of either extremum, or an insertion, is O(log n).

**Comment by asafigan** [comment]
Oh, wow! That looks perfect! I didn't even think to look for different data structures. Thanks!
