### ISSUE TITLE
with_capacity_by is not expected

### ISSUE THREAD

**Issue by xingzhicn** [sekineh/binary-heap-plus-rs#9]
I want to create a Binary Heap of fixed length，but the length is not expected.
```
    // custom-sort heap
    let mut heap1 = BinaryHeap::with_capacity_by(2,|a: &(i32,i32), b: &(i32,i32)| b.1.cmp(&a.1));
    heap1.push((1,5));
    heap1.push((3,2));
    heap1.push((2,1));
    heap1.push((1,1));
    heap1.push((1,0));
    assert_eq!(heap1.pop(), Some((1,0))); // min value
    assert_eq!(heap1.pop(), Some((2,1))); // min value
    assert_eq!(heap1.pop(), Some((1,1))); // min value
    assert_eq!(heap1.pop(), Some((3,2))); // min value
```

**Comment by sekineh** [comment]
Hi,

`BinaryHeap::with_capacity_by()` does not limit the actual length of the heap.
It behaves exactly like `Vec::with_capacity()` which allocate the capacity beforehand to avoid later reallocation. 

For more explanation, please read the docs below:
- https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity
- https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation
- https://docs.rs/binary-heap-plus/0.2.0/binary_heap_plus/struct.BinaryHeap.html#method.with_capacity_by
> This preallocates enough memory for capacity elements, so that the BinaryHeap does not have to be reallocated until it contains at least that many values.

If you want to limit the actual length of any `BinaryHeap` or `Vec`, you need to check `.len()` before `push`ing element onto it.  I believe you can write a thin wrapper that perform this operation automatically.
